var Explosion1="",Explosion2="",ExplosionOpen=!1,ExplosionCheck="322561",db=firebase.firestore(),snd=new Audio("balarm.wav");snd.loop=!0;
function ExplosionStart(a){console.log("\u555f\u52d5\u8b66\u5831");ExplosionCheck=a;switch(a){case Explosion1:db.collection("Yafeng").doc("AlarmTime").update({ExplosionOpen1:!0}).then(function(){console.log("\u66f4\u65b0Explosion1\u72c0\u614b\u5b8c\u6210\uff0c\u6a19\u8a18\u70ba\u5df2\u8b66\u5831")});break;case Explosion2:db.collection("Yafeng").doc("AlarmTime").update({ExplosionOpen2:!0}).then(function(){console.log("\u66f4\u65b0Explosion2\u72c0\u614b\u5b8c\u6210\uff0c\u6a19\u8a18\u70ba\u5df2\u8b66\u5831")})}ExplosionUpdate();ExplosionOpen=
!0;document.styleSheets[0].addRule("#app::before","animation-duration:1.5s;animation-iteration-count:infinite");document.getElementById("StopBtn").style.display="block";document.getElementById("ChangeBtn").style.display="none";snd.play()}
function ExplosionStop(){console.log("\u95dc\u9589\u8b66\u5831");ExplosionOpen=!1;document.styleSheets[0].addRule("#app::before","animation-duration:1.5s;animation-iteration-count:0");document.getElementById("StopBtn").style.display="none";document.getElementById("ChangeBtn").style.display="inline-block";snd.pause();snd.currentTime=0}
function ExplosionUpdate(){db.collection("Yafeng").doc("AlarmTime").get().then(function(a){if(a.exists){var c=0,b=0;1==a.data().ExplosionOpen1&&(c+=1);1==a.data().ExplosionOpen2&&(c+=1);"999999"!=a.data().Explosion1&&(b+=1);"999999"!=a.data().Explosion2&&(b+=1);document.getElementById("SpanCount").innerText=c+"/"+b}else console.log("\u627e\u4e0d\u5230ExplosionOpen")})["catch"](function(a){console.log("\u8b80\u53d6ExplosionOpen\u5931\u6557\uff1a",a)})}function StopBtnClick(){ExplosionStop()}
var padDate=function(a){return 10>a?"0"+a:a},app=new Vue({el:"#app",data:{date:new Date},filters:{formatDate:function(a){var c=new Date;a=c.getFullYear();var b=padDate(c.getMonth()+1),e=padDate(c.getDate()),d=padDate(c.getHours()),g=padDate(c.getMinutes());c=padDate(c.getSeconds());var f=e.toString()+d.toString()+g.toString();f==Explosion1||f==Explosion2?f!=ExplosionCheck&&0==ExplosionOpen&&ExplosionStart(f):1==ExplosionOpen&&ExplosionStop();return a+"-"+b+"-"+e+" "+d+":"+g+":"+c}},mounted:function(){var a=
this;this.timer=setInterval(function(){a.date=new Date},1E3)},beforeDestory:function(){this.timer&&clearInterval(this.timer)}}),date=new Date,year=date.getFullYear(),month=padDate(date.getMonth()+1),day=padDate(date.getDate()),hours=padDate(date.getHours()),minutes=padDate(date.getMinutes()),seconds=padDate(date.getSeconds()),isIE=-1<navigator.userAgent.search("MSIE"),isIE7=-1<navigator.userAgent.search("MSIE 7"),isFirefox=-1<navigator.userAgent.search("Firefox"),isOpera=-1<navigator.userAgent.search("Opera"),
isSafari=-1<navigator.userAgent.search("Safari");isIE7&&(browser="IE7");isIE&&(browser="IE");isFirefox&&(browser="Firefox");isOpera&&(browser="Opera");isSafari&&(browser="Safari/Chrome");db.collection("Record").doc(year+"-"+month+"-"+day+" "+hours+":"+minutes+":"+seconds).set({Browser:browser}).then(function(a){})["catch"](function(a){console.error("\u8a18\u9304\u932f\u8aa4\uff1a",a)});
db.collection("Yafeng").doc("AlarmTime").onSnapshot(function(a){console.log("\u66f4\u65b0\u8cc7\u6599\u4e2d...");ExplosionUpdate();if(a.exists)if(console.log("\u6700\u8fd1\u66f4\u65b0\u8b66\u5831\u6642\u9593\u70ba",a.data().UpdateYM),year+month.toString()==a.data().UpdateYM)console.log("\u5224\u65b7\u672c\u6708\u5df2\u6709\u66f4\u65b0\u8b66\u5831"),Explosion1=a.data().Explosion1,Explosion2=a.data().Explosion2;else{console.log("\u5224\u65b7\u672c\u6708\u6c92\u6709\u66f4\u65b0\u8b66\u5831\uff0c\u5c07\u9032\u884c\u66f4\u65b0...");
a=function(){var a=(new Date(year,month,0)).getDate(),b=day,e=padDate(Math.floor(Math.random()*(a-b+1))+b);a=17;b=9;do var d=padDate(Math.floor(Math.random()*(a-b+1))+b);while(12==d);b=0;a=padDate(Math.floor(Math.random()*(59-b+1))+b);return e.toString()+d.toString()+a.toString()};do Explosion1=a();while(Explosion1<=day.toString()+hours.toString()+minutes.toString());if(24<day)Explosion2="999999";else{do{do Explosion2=a();while(Explosion2<=day.toString()+hours.toString()+minutes.toString())}while(3>
Math.abs(Number(Explosion1.substr(0,2))-Number(Explosion2.substr(0,2))))}db.collection("Yafeng").doc("AlarmTime").update({UpdateYM:year+month.toString(),Explosion1:Explosion1,Explosion2:Explosion2,ExplosionOpen1:!1,ExplosionOpen2:!1}).then(function(){console.log("\u66f4\u65b0\u672c\u6708\u8b66\u5831\u6642\u9593\u5b8c\u6210!")})}else console.log("\u627e\u4e0d\u5230UpdateYM")})["catch"](function(a){console.log("\u8b80\u53d6UpdateYM\u5931\u6557\uff1a",a)});